name: Build cloudflared Linux amd64

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Linux amd64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Enable Go modules
        run: go env -w GO111MODULE=on

      - name: Build static binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=test" -o bin/cloudflared ./cmd/cloudflared

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-linux-amd64
          path: bin/cloudflared
